# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15GiAKElxTqwd-lcOz1fIMP9_v7JNJhjy
"""

import streamlit as st
import tensorflow as tf
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# Load the trained model
model = tf.keras.models.load_model("energy_demand_model.h5", custom_objects={"mse": tf.keras.losses.MeanSquaredError()})

# Streamlit UI
st.title("Energy Demand Predictor")
st.write("Enter values to predict future energy consumption.")

# Input fields for user
hour = st.number_input("Hour (0-23)", min_value=0, max_value=23, value=12)
day = st.number_input("Day (1-31)", min_value=1, max_value=31, value=15)
month = st.number_input("Month (1-12)", min_value=1, max_value=12, value=6)
weekday = st.number_input("Weekday (0=Monday, 6=Sunday)", min_value=0, max_value=6, value=2)
coal = st.number_input("Coal Generation (MW)", value=1000.0)
nuclear = st.number_input("Nuclear Generation (MW)", value=5000.0)
ccgt = st.number_input("CCGT Generation (MW)", value=3000.0)
wind = st.number_input("Wind Generation (MW)", value=2000.0)
solar = st.number_input("Solar Generation (MW)", value=1500.0)
hydro = st.number_input("Hydro Generation (MW)", value=500.0)
biomass = st.number_input("Biomass Generation (MW)", value=300.0)

# Prepare input data
input_data = np.array([[hour, day, month, weekday, coal, nuclear, ccgt, wind, solar, hydro, biomass]])
scaler = MinMaxScaler()
input_data = scaler.fit_transform(input_data)

# Predict button
if st.button("Predict Energy Demand"):
    prediction = model.predict(input_data)
    st.success(f"Predicted Energy Demand: {prediction[0][0]:.2f} MW")